=== sodamachinebroke/IIJU0Z_XML/XMLTaskIIJU0Z/XSDiiju0z.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

  <!-- Subscribers -->
  <xs:complexType name="subscriberType">
    <xs:sequence>
      <xs:element name="phone" type="xs:string"/>
      <xs:element name="email" type="xs:string" maxOccurs="unbounded"/>
      <xs:element name="sub_addr" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="sub_id" type="xs:string" use="required"/>
  </xs:complexType>

  <!-- Bills -->
  <xs:complexType name="billType">
    <xs:sequence>
      <xs:element name="plan_no" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="bill_sub" type="xs:string" use="required"/>
    <xs:attribute name="bill_plan" type="xs:string" use="required"/>
  </xs:complexType>

  <!-- Plans -->
  <xs:complexType name="planType">
    <xs:sequence>
      <xs:element name="ZIP" type="xs:string"/>
      <xs:element name="city" type="xs:string"/>
      <xs:element name="str" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="p_id" type="xs:string" use="required"/>
  </xs:complexType>

  <!-- Services -->
  <xs:complexType name="serviceType">
    <xs:sequence>
      <xs:element name="price_sum" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="serv_sum" type="xs:string" use="required"/>
    <xs:attribute name="tel_s" type="xs:string" use="required"/>
    <xs:attribute name="int_s" type="xs:string" use="required"/>
    <xs:attribute name="tv_s" type="xs:string" use="required"/>
  </xs:complexType>

  <!-- Telephone plan types -->
  <xs:complexType name="telephonePlanType">
    <xs:sequence>
      <xs:element name="data_GB" type="xs:string"/>
      <xs:element name="free_mins" type="xs:string"/>
      <xs:element name="price" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="tel_id" type="xs:string" use="required"/>
  </xs:complexType>

  <!-- Internet plan types -->
  <xs:complexType name="internetPlanType">
    <xs:sequence>
      <xs:element name="bwidth" type="xs:integer"/>
      <xs:element name="technology" type="xs:string"/>
      <xs:element name="price" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="i_id" type="xs:string" use="required"/>
  </xs:complexType>

  <!-- TV plan types -->
  <xs:complexType name="tvPlanType">
    <xs:sequence>
      <xs:element name="ch_num" type="xs:integer"/>
      <xs:element name="hd_num" type="xs:integer"/>
      <xs:element name="sd_num" type="xs:integer"/>
      <xs:element name="price" type="xs:integer"/>
    </xs:sequence>
    <xs:attribute name="tv_id" type="xs:string" use="required"/>
  </xs:complexType>

  <!-- Root element -->
  <xs:element name="telecommunications">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="subscribers" type="subscriberType" maxOccurs="unbounded"/>
        <xs:element name="bill" type="billType" maxOccurs="unbounded"/>
        <xs:element name="plan" type="planType" maxOccurs="unbounded"/>
        <xs:element name="service" type="serviceType" maxOccurs="unbounded"/>
        <xs:element name="telephone_plan" type="telephonePlanType" maxOccurs="unbounded"/>
        <xs:element name="internet_plan" type="internetPlanType" maxOccurs="unbounded"/>
        <xs:element name="tv_plan" type="tvPlanType" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== sodamachinebroke/IIJU0Z_XML/XMLTaskIIJU0Z/DOMParseiiju0z/XMLiiju0z.xml
<?xml version="1.0" encoding="UTF-8"?>

<telecommunications xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XSDiiju0z.xsd">


    <!-- Subscribers -->
    <!-- begin -->
    <subscriber sub_id="0001">
        <email>piroskaneni@piroskaneni.hu</email>
        <email>piroskaburner@gmail.com</email>
        <email>piros@freemail.hu</email>
        <phone>+36466748449</phone>
        <address>
            <ZIP>3467</ZIP>
            <city>Ároktő</city>
            <str>Kossuth Lajos út 3</str>
        </address>
    </subscriber>
    <subscriber sub_id="0002">

        <email>istvan@gmail.com</email>
        <email>akiraly@citromail.hu</email>
        <email>istvankiraly@allamalapitas.hu</email>
        <phone>+36204567892</phone>
        <address>
            <ZIP>2435</ZIP>
            <city>Nagylók</city>
            <str>Szent István út 1001</str>
        </address>
    </subscriber>

    <subscriber sub_id="0003">

        <email>geza@gmail.com</email>
        <email>fejedelem@citromail.hu</email>
        <email>honfoglalas@magyarorszag.hu</email>
        <phone>+36204567893</phone>
        <address>
            <ZIP>2434</ZIP>
            <city>Hantos</city>
            <str>Kossuth Lajos út 2</str>
        </address>
    </subscriber>
    <!-- end -->

    <!-- Bills -->
    <!-- begin -->
    <bill bill_sub="0001" bill_plan="34670001">
        <plan_no>1</plan_no>
    </bill>
    <bill bill_sub="0001" bill_plan="34670002">
        <plan_no>2</plan_no>
    </bill>
    <bill bill_sub="0002" bill_plan="24350001">
        <plan_no>1</plan_no>
    </bill>
    <bill bill_sub="0003" bill_plan="24340001">
        <plan_no>1</plan_no>
    </bill>
    <!-- end -->

    <!-- Plans -->
    <!-- begin -->
    <plan p_id="34670001">
        <address>
            <ZIP>3467</ZIP>
            <city>Ároktő</city>
            <str>Kossuth Lajos út 3</str>
        </address>

    </plan>

    <plan p_id="34670002">
        <address>
            <ZIP>3592</ZIP>
            <city>Nemesbikk</city>
            <str>Posta utca 13</str>
        </address>

    </plan>

    <plan p_id="24350001">
        <address>
            <ZIP>2435</ZIP>
            <city>Nagylók</city>
            <str>Szent István út 1001</str>
        </address>

    </plan>

    <plan p_id="24340001">
        <address>
            <ZIP>2220</ZIP>
            <city>Vecsés</city>
            <str>Gárdony Géza utca 10</str>
        </address>

    </plan>
    <!-- end -->

    <!-- Services -->
    <!-- begin -->

    <service serv_sum="34670001" tel_serv="5120" i_serv="Cu120" tv_serv="5050">
        <price_sum>9500</price_sum>
    </service>

    <service serv_sum="34670002" tel_serv="5120" i_serv="Co500" tv_serv="5050">
        <price_sum>12500</price_sum>
    </service>

    <service serv_sum="24350001" tel_serv="00" i_serv="Op1000">
        <price_sum>19000</price_sum>
    </service>
    <service serv_sum="24340001" tel_serv="5050" i_serv="Co500" tv_serv="2030">
        <price_sum>12000</price_sum>
    </service>

    <!-- end -->

    <!-- Internet plan types-->
    <!-- begin -->
    <internet i_id="Cu120">
        <technology>copper</technology>
        <bwidth>120</bwidth>
        <price>2000</price>
    </internet>

    <internet i_id="Co500">
        <technology>coaxial</technology>
        <bwidth>500</bwidth>
        <price>5000</price>
    </internet>

    <internet i_id="Op1000">
        <technology>optical</technology>
        <bwidth>1000</bwidth>
        <price>9000</price>
    </internet>
    <!-- end -->

    <!-- Telephone plan types -->
    <!-- begin -->
    <telephone tel_id="5120">
        <data_GB>5</data_GB>
        <free_mins>120</free_mins>
        <price>3500</price>
    </telephone>

    <telephone tel_id="5050">
        <data_GB>50</data_GB>
        <free_mins>50</free_mins>
        <price>5000</price>
    </telephone>

    <telephone tel_id="00">
        <data_GB>-1</data_GB>
        <free_mins>-1</free_mins>
        <price>10000</price>
    </telephone>
    <!-- end -->



    <!-- TV plan types -->
    <!-- begin -->
    <tv tv_id="2030">
        <ch_num>50</ch_num>
        <sd_num>30</sd_num>
        <hd_num>20</hd_num>
        <price>2000</price>
    </tv>

    <tv tv_id="5050">
        <ch_num>100</ch_num>
        <sd_num>50</sd_num>
        <hd_num>50</hd_num>
        <price>4000</price>
    </tv>

</telecommunications>

=== sodamachinebroke/IIJU0Z_XML/XMLTaskIIJU0Z/XMLiiju0z.xml
<?xml version="1.0" encoding="UTF-8"?>

<telecommunications xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xs:noNamespaceSchemaLocation="XSDiiju0z.xsd">


    <!-- Subscribers -->
    <!-- begin -->
    <subscribers sub_id="0001">
        <phone>+36466748449</phone>
        <email>piroskaneni@piroskaneni.hu</email>
        <email>piroskaburner@gmail.com</email>
        <email>piros@freemail.hu</email>
        <sub_addr>3467 Ároktő Kossuth Lajos út 3</sub_addr>
    </subscribers>
    <subscribers sub_id="0002">
        <phone>+36204567892</phone>
        <email>istvan@gmail.com</email>
        <email>akiraly@citromail.hu</email>
        <email>istvankiraly@allamalapitas.hu</email>
        <sub_addr>2435 Nagylók Szent István út 1001</sub_addr>
    </subscribers>

    <subscribers sub_id="0003">
        <phone>+36204567893</phone>
        <email>geza@gmail.com</email>
        <email>fejedelem@citromail.hu</email>
        <email>honfoglalas@magyarorszag.hu</email>
        <sub_addr>2434 Hantos Kossuth Lajos út 2</sub_addr>
    </subscribers>
    <!-- end -->

    <!-- Bills -->
    <!-- begin -->
    <bill bill_sub="0001" bill_plan="34670001">
        <plan_no>1</plan_no>
    </bill>
    <bill bill_sub="0001" bill_plan="34670002">
        <plan_no>2</plan_no>
    </bill>
    <bill bill_sub="0002" bill_plan="24350001">
        <plan_no>1</plan_no>
    </bill>
    <bill bill_sub="0003" bill_plan="24340001">
        <plan_no>1</plan_no>
    </bill>
    <!-- end -->

    <!-- Plans -->
    <!-- begin -->
    <plan p_id="34670001">
        <ZIP>3467</ZIP>
        <city>Ároktő</city>
        <str>Kossuth Lajos út 3</str>
    </plan>

    <plan p_id="34670002">
        <ZIP>3592</ZIP>
        <city>Nemesbikk</city>
        <str>Posta utca 13</str>
    </plan>

    <plan p_id="24350001">
        <ZIP>2435</ZIP>
        <city>Nagylók</city>
        <str>Szent István út 1001</str>
    </plan>

    <plan p_id="24340001">
        <ZIP>2220</ZIP>
        <city>Vecsés</city>
        <str>Gárdony Géza utca 10</str>
    </plan>
    <!-- end -->

    <!-- Services -->
    <!-- begin -->

    <service serv_sum="34670001" tel_s="5120" int_s="Cu120" tv_s="5050">
        <price_sum>9500</price_sum>
    </service>

    <service serv_sum="34670002" tel_s="5120" int_s="Co500" tv_s="5050">
        <price_sum>12500</price_sum>
    </service>

    <service serv_sum="24350001" tel_s="00" int_s="Op1000" tv_s="">
        <price_sum>19000</price_sum>
    </service>
    <service serv_sum="24340001" tel_s="5050" int_s="Co500" tv_s="2030">
        <price_sum>12000</price_sum>
    </service>

    <!-- end -->

    <!-- Telephone plan types -->
    <!-- begin -->
    <telephone_plan tel_id="5120">
        <data_GB>5</data_GB>
        <free_mins>120</free_mins>
        <price>3500</price>
    </telephone_plan>

    <telephone_plan tel_id="5050">
        <data_GB>50</data_GB>
        <free_mins>50</free_mins>
        <price>5000</price>
    </telephone_plan>

    <telephone_plan tel_id="00">
        <data_GB>unlimited</data_GB>
        <free_mins>unlimited</free_mins>
        <price>10000</price>
    </telephone_plan>
    <!-- end -->

    <!-- Internet plan types-->
    <!-- begin -->
    <internet_plan i_id="Cu120">
        <bwidth>120</bwidth>
        <technology>copper</technology>
        <price>2000</price>
    </internet_plan>

    <internet_plan i_id="Co500">
        <bwidth>500</bwidth>
        <technology>coaxial</technology>
        <price>5000</price>
    </internet_plan>

    <internet_plan i_id="Op1000">
        <bwidth>1000</bwidth>
        <technology>optical</technology>
        <price>9000</price>
    </internet_plan>
    <!-- end -->

    <!-- TV plan types -->
    <!-- begin -->
    <tv_plan tv_id="2030">
        <ch_num>50</ch_num>
        <hd_num>20</hd_num>
        <sd_num>30</sd_num>
        <price>2000</price>
    </tv_plan>

    <tv_plan tv_id="5050">
        <ch_num>100</ch_num>
        <hd_num>50</hd_num>
        <sd_num>50</sd_num>
        <price>4000</price>
    </tv_plan>

</telecommunications>
