<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE iiju0z_orarend [
  <!ELEMENT iiju0z_orarend (ora+)>
  <!ELEMENT ora (targy, idopont, helyszin, oktato, szak)>
  <!ATTLIST ora
    id CDATA #REQUIRED
    tipus CDATA #REQUIRED
  >
  <!ELEMENT targy (#PCDATA)>
  <!ELEMENT idopont (nap, tol, ig)>
  <!ELEMENT helyszin (#PCDATA)>
  <!ELEMENT oktato (#PCDATA)>
  <!ELEMENT szak (#PCDATA)>
  <!ELEMENT nap (#PCDATA)>
  <!ELEMENT tol (#PCDATA)>
  <!ELEMENT ig (#PCDATA)>
]>

<iiju0z_orarend>
    <ora id="1" tipus="Előadás">
        <targy>Lineáris Algebra Numerikus módszerei</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>8:00</tol>
            <ig>10:00</ig>
        </idopont>
        <helyszin>A1 218</helyszin>
        <oktato>Karácsony Zsolt</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="2" tipus="Gyakorlat">
        <targy>Lineáris Algebra Numerikus módszerei</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>Inf 103</helyszin>
        <oktato>Karácsony Zsolt</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="3" tipus="Előadás">
        <targy>Adatkezelés XML nyelven</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>12:00</tol>
            <ig>14:00</ig>
        </idopont>
        <helyszin>A1 XXXII</helyszin>
        <oktato>Bednarik Lácló</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="4" tipus="Előadás">
        <targy>Algoritmusok és Vizsgálatuk</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>14:00</tol>
            <ig>16:00</ig>
        </idopont>
        <helyszin>A1 320.</helyszin>
        <oktato>Dr. Házy Attila</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="5" tipus="Előadás">
        <targy>Algoritmusok és Vizsgálatuk</targy>
        <idopont>
            <nap>Kedd</nap>
            <tol>16:00</tol>
            <ig>18:00</ig>
        </idopont>
        <helyszin>A1 320</helyszin>
        <oktato>Dr. Házy Attila</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="6" tipus="Gyakorlat">
        <targy>Adatkezelés XML nyelven</targy>
        <idopont>
            <nap>Szerda</nap>
            <tol>10:00</tol>
            <ig>12:00</ig>
        </idopont>
        <helyszin>Inf 101</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
    <ora id="7" tipus="Gyakorlat">
        <targy>Játékprototípusok</targy>
        <idopont>
            <nap>Csütörtök</nap>
            <tol>16:00</tol>
            <ig>20:00</ig>
        </idopont>
        <helyszin>Inf 15</helyszin>
        <oktato>Kiss Áron</oktato>
        <szak>Programtervező informatikus</szak>
    </ora>
</iiju0z_orarend>