=== sodamachinebroke/IIJU0Z_XML/iiju0z_0927/BSZK_kurzusfelvetel.dtd
<!ELEMENT kurzusfelvetel (hallgato, kurzusok)>

    <!ATTLIST kurzusfelvetel
        tanev CDATA #REQUIRED
        egyetem CDATA #FIXED "ME">

    <!ELEMENT hallgato (hnev, szulev, szak+)>
        <!ATTLIST hallgato id ID #REQUIRED>

    <!ELEMENT hnev (#PCDATA)>
    <!ELEMENT szulev (#PCDATA)>
    <!ELEMENT szak (#PCDATA)>
        <!ATTLIST szak evf CDATA #REQUIRED>

    <!ELEMENT kurzusok (kurzus*)>
    <!ELEMENT kurzus (kurzusnev, kredit, hely, idopont, oktato, oraado?)>
        <!ATTLIST kurzus
            id ID #REQUIRED
            jovahagyas (igen | nem) "nem"
            nyelv CDATA #IMPLIED>

    <!ELEMENT kurzusnev (#PCDATA)>
    <!ELEMENT kredit (#PCDATA)>
    <!ELEMENT hely (#PCDATA)>
    <!ELEMENT idopont (#PCDATA)>
    <!ELEMENT oktato (#PCDATA)>
    <!ELEMENT oraado (#PCDATA)>

=== sodamachinebroke/IIJU0Z_XML/iiju0z_0927/BSZK_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE kurzusfelvetel SYSTEM "BSZK_kurzusfelvetel.dtd">

<kurzusfelvetel tanev="2022_2023 I." egyetem="ME">

    <hallgato id="KPRLNM.ME">
        <hnev>Babik Szilárd Kristóf</hnev>
        <szulev>2002-02-08</szulev>
        <szak evf="5">Programtervező informatikus</szak>
    </hallgato>

    <kurzusok>
        <kurzus id="GEIAL322-B" nyelv="magyar">
            <kurzusnev>Adatkezelés XML környezetben</kurzusnev>
            <kredit>5</kredit>
            <hely>XXXII.</hely>
            <idopont>Kedd 12:00-14:00</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>
        <kurzus id="GEMAK234-B">
            <kurzusnev>Algoritmusok és vizsgálatuk</kurzusnev>
            <kredit>5</kredit>
            <hely>X.</hely>
            <idopont>Kedd 14:00-18:00</idopont>
            <oktato>Dr. Házy Attila</oktato>
        </kurzus>
        <kurzus id="GEIAK130-B" jovahagyas="igen">
            <kurzusnev>Mesterséges intelligencia alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>II.</hely>
            <idopont>Kedd 9:00-12:00</idopont>
            <oktato>Dr. Kunné Tamás Judit</oktato>
            <oraado>Fazekas Levente</oraado>
        </kurzus>
    </kurzusok>
</kurzusfelvetel>
